import { Job, Training, BlogPost, Testimonial } from './types';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Product Designer',
    company: 'TechCorp',
    location: 'San Francisco, CA',
    salary: { min: 120000, max: 160000 },
    type: 'Full-time',
    experience: 'Senior',
    category: 'Design',
    description: 'We\'re looking for an experienced Senior Product Designer to lead our design system and shape the future of our product.',
    requirements: [
      ' 5+ years of product design experience',
      'Expert in design systems',
      'Strong communication skills',
      'Experience with Figma and prototyping tools',
    ],
    benefits: [
      'Competitive salary',
      'Health insurance',
      'Remote work',
      'Stock options',
    ],
    featured: true,
    status: 'open',
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    applicants: 24,
  },
  {
    id: '2',
    title: 'Full Stack Engineer',
    company: 'StartupXYZ',
    location: 'Remote',
    salary: { min: 100000, max: 140000 },
    type: 'Full-time',
    experience: 'Mid-Level',
    category: 'Engineering',
    description: 'Join our growing engineering team and build scalable web applications.',
    requirements: [
      '3+ years of full stack development',
      'Strong React and Node.js skills',
      'Experience with databases',
      'Git proficiency',
    ],
    benefits: [
      'Competitive salary',
      'Health insurance',
      'Flexible schedule',
      'Professional development',
    ],
    featured: true,
    status: 'open',
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    applicants: 47,
  },
  {
    id: '3',
    title: 'Marketing Manager',
    company: 'GlobalBrand',
    location: 'New York, NY',
    salary: { min: 80000, max: 110000 },
    type: 'Full-time',
    experience: 'Mid-Level',
    category: 'Marketing',
    description: 'Lead our marketing initiatives and drive growth through innovative campaigns.',
    requirements: [
      '4+ years of marketing experience',
      'Digital marketing expertise',
      'Strong analytical skills',
      'Team leadership experience',
    ],
    benefits: [
      'Competitive salary',
      'Health insurance',
      'Flexible work',
      'Career growth',
    ],
    featured: false,
    status: 'open',
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    applicants: 15,
  },
  {
    id: '4',
    title: 'Data Scientist',
    company: 'DataCorp',
    location: 'Boston, MA',
    salary: { min: 110000, max: 150000 },
    type: 'Full-time',
    experience: 'Senior',
    category: 'Engineering',
    description: 'Analyze complex datasets and build machine learning models.',
    requirements: [
      '5+ years of data science experience',
      'Python and R expertise',
      'ML frameworks knowledge',
      'Statistical analysis skills',
    ],
    benefits: [
      'Competitive salary',
      'Equity package',
      'Remote work',
      'Learning budget',
    ],
    featured: false,
    status: 'open',
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    applicants: 32,
  },
  {
    id: '5',
    title: 'UX Researcher',
    company: 'DesignStudio',
    location: 'Austin, TX',
    salary: { min: 90000, max: 130000 },
    type: 'Full-time',
    experience: 'Mid-Level',
    category: 'Design',
    description: 'Conduct user research and inform design decisions through insights.',
    requirements: [
      '3+ years of UX research',
      'Qualitative and quantitative methods',
      'User testing expertise',
      'Communication skills',
    ],
    benefits: [
      'Competitive salary',
      'Health insurance',
      'Flexible hours',
      'Conference budget',
    ],
    featured: false,
    status: 'open',
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    applicants: 19,
  },
];

export const mockTraining: Training[] = [
  {
    id: '1',
    title: 'Advanced React Patterns',
    category: 'Engineering',
    level: 'Advanced',
    instructor: 'John Smith',
    price: 199,
    rating: 4.8,
    students: 1250,
    description: 'Master advanced React patterns and best practices.',
    curriculum: [
      'React Hooks deep dive',
      'Custom hooks',
      'Context API optimization',
      'Performance optimization',
      'Real-world patterns',
    ],
    duration: 24,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
  },
  {
    id: '2',
    title: 'Figma for Product Design',
    category: 'Design',
    level: 'Beginner',
    instructor: 'Sarah Johnson',
    price: 149,
    rating: 4.9,
    students: 2100,
    description: 'Learn professional product design using Figma.',
    curriculum: [
      'Figma basics',
      'Design systems',
      'Prototyping',
      'Collaboration features',
      'Best practices',
    ],
    duration: 18,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
  },
  {
    id: '3',
    title: 'Data Science Masterclass',
    category: 'Engineering',
    level: 'Advanced',
    instructor: 'Dr. Michael Chen',
    price: 299,
    rating: 4.7,
    students: 850,
    description: 'Comprehensive data science and machine learning course.',
    curriculum: [
      'Python fundamentals',
      'Data analysis',
      'ML algorithms',
      'Deep learning',
      'Real-world projects',
    ],
    duration: 40,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Future of Product Design',
    slug: 'future-of-product-design',
    author: 'Sarah Johnson',
    category: 'Design',
    content: 'Exploring emerging trends in product design and user experience.',
    excerpt: 'Discover the latest trends shaping the future of product design.',
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    readTime: 5,
  },
  {
    id: '2',
    title: 'React 19: What\'s New?',
    slug: 'react-19-whats-new',
    author: 'John Smith',
    category: 'Engineering',
    content: 'Comprehensive overview of new features in React 19.',
    excerpt: 'Learn about the latest updates and improvements in React 19.',
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    readTime: 8,
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    author: 'Alex Chen',
    role: 'Product Manager',
    company: 'TechCorp',
    content: 'CareerHub helped me land my dream job. The platform is intuitive and well-designed.',
    rating: 5,
  },
  {
    id: '2',
    author: 'Emily Rodriguez',
    role: 'Senior Designer',
    company: 'DesignStudio',
    content: 'Great training courses and job listings. Highly recommended!',
    rating: 5,
  },
  {
    id: '3',
    author: 'Michael Chang',
    role: 'Data Scientist',
    company: 'DataCorp',
    content: 'The platform has everything I need for career development.',
    rating: 4,
  },
];

// Utility function to get mock data with pagination
export function getMockJobsWithPagination(page: number = 1, pageSize: number = 10) {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  return {
    data: mockJobs.slice(start, end),
    total: mockJobs.length,
    page,
    pageSize,
    totalPages: Math.ceil(mockJobs.length / pageSize),
  };
}

export function getMockTrainingWithPagination(page: number = 1, pageSize: number = 10) {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  return {
    data: mockTraining.slice(start, end),
    total: mockTraining.length,
    page,
    pageSize,
    totalPages: Math.ceil(mockTraining.length / pageSize),
  };
}
